### ISSUE TITLE
Sync Existing Records to Local Salesforce Table?

### ISSUE THREAD

**Issue by jsznap** [roblesterjr04/EloquentSalesForce#104]
Is it possible to sync existing records to local table, for quick access? Or are only newly created records accessible via the local sync feature?

**Comment by jsznap** [comment]
Bump? How can I take an existing found record, add them to DB and have them sync with SF? The only way I have found is to use a DB command to insert the record, otherwise it just attempts to create the record as new or fails to pass integrity checks because record exists. Just sort of a pain to find the record, check if it exists and insert it for each object. Would be nicer if you could query the table and if it doesn't exist, to check SF for the record then import/return that record.

**Comment by roblesterjr04** [comment]
Hey folks. This is documented, there's a trait you can add to your model! :)

https://roblesterjr04.github.io/EloquentSalesForce/index.html#/?id=local-sync-new

Let me know if this isn't what you're asking for.

This uses the local model as the source of truth, but the config file lets you enable a 2 way sync.

Generally the functions assume the data does not exist on SF - so it will attempt to create the SF data, then store the ID it receives back. one non-documented requirement is a field on your local model to store the SF ID. It must be named `salesforce`, or you must re-define it in your model: 

```php
protected $salesForceIdField = '{some id of a field}';
```

**Comment by jsznap** [comment]
If I query the model, and the record doesn't exist there, but does exist in salesforce, it won't automatically pull it down correctly? Essentially i need to check local, if false, also check salesforce remote model?

**Comment by roblesterjr04** [comment]
right, its not able to check SF like that. However, if you turn on 2 way sync, and instantiate an empty model (say, by using the `firstOrNew` method), you could trigger it to pull from SF and then just save it, maybe with some custom observer and logic.

**Comment by jsznap** [comment]
Okay Thank you.
