### ISSUE TITLE
pull token from DB and use it

### ISSUE THREAD

**Issue by Arametheus** [roblesterjr04/EloquentSalesForce#105]
@roblesterjr04 I'm trying to pull a stored Token from the Database and update the authentification that this package is using.

reason I'm doing this is the new api standard for SF is to get token and then refresh it. (basically webserver) but I want to do it on behave of the user once I have there token stored.

so I was wondering is this possible in some way thru the SObjects authenticate()??

I was trying to go down the path of making my own service provider and interrupting  Forrest config to pull from my service provider.

`<?php
namespace App\Services;

use App\Helpers\AuthHelper;
use App\Models\UserPlatformAccesses;
use Omniphx\Forrest\Interfaces\StorageInterface;
use App\Http\Controllers\Providers\SalesforceController;

class SalesforceDatabaseStorage implements StorageInterface
{public function put($key, $value)
    {}

    public function get($key)
    {}

    public function has($key)
    {}

    public function forget($key)
    {}
}`

then in my eloquent_sf
I changed storage to 
'storage' => [
            'type' => \App\Services\SalesforceDatabaseStorage::class, // 'session' or 'cache' are the two options
            'path' => 'forrest_', // unique storage path to avoid collisions
            'expire_in' => 20, // number of minutes to expire cache/session
            'store_forever' => false, // never expire cache/session
        ],

but I get this error
Non-static method App\Services\SalesforceDatabaseStorage::has() cannot be called statically

so I changed my method to public static then it gives me an error I can't change it to static.. really confusing.  which I don't know if this would even work in the end.

then I saw your SObjects and thought maybe that would be the better way to go but not sure where to start so it takes my stored token first since then I could grab my token make sure its not expired if it is refresh it and then send it to authenticate.

Thanks for any help on this as this package as worked great until I needed to switch it pulling from the DB instead of updating my password every time it expired.

**Comment by roblesterjr04** [comment]
This is some fundamental stuff honestly. SObjects is set up with a Facade, which is something Laravel takes care of to handle the fuzzy static/dynamic calls. But the answer is, keep the method non-static like you have above, but instantiate your service class and call it with an arrow `->`

```php
$service = new \App\Services\SalesforceDatabaseStorage();

$service->has(...
```
