### ISSUE TITLE
Uploading files to objects

### ISSUE THREAD

**Issue by blorange2** [roblesterjr04/EloquentSalesForce#108]
Hi,

This package is awesome but I have a random question that might not even be possible?

In Salesforce there are attachments, but could I use this package to add attachments to an object?

I'd like to generate a document in my application and pass it back to Salesforce as an attachment to an object.

Thanks very much

**Comment by blorange2** [comment]
I figured the solution was to use the SObject class.

**Comment by stzahi** [comment]
@blorange2 , can you please tell me more about the solution you've found? Or maybe a reference to the solution please?

**Comment by blorange2** [comment]
> @blorange2 , can you please tell me more about the solution you've found? Or maybe a reference to the solution please?

Yes, sorry, that was my bad

```
SObjects::sobjects('Attachment', [
        'method' => 'post',
        'body' => [
            'ParentId' => '0032z00000G5wGvAAJ',
            'Name' => 'Test',
            'Description' => 'This is a test attachment.',
            'Body' => base64_encode(file_get_contents(__DIR__ . '/test-attachment.txt')),

        ]
    ])
```

I listed all the object types and then was looking at how to add attachments, turns out you have to base 64 encode the raw file.

I got the information I needed from here: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_insert_update_blob.htm

**Comment by stzahi** [comment]
Thank you very much! it is very useful.
