### ISSUE TITLE
Picklist Values

### ISSUE THREAD

**Issue by jayomayan** [roblesterjr04/EloquentSalesForce#11]
How can I pull/query the values of a picklist?

**Comment by seankndy** [comment]
You could do somthing like this:

`    public static function getPicklistValues($object, $field)
    {
        Forrest::authenticate();
        $desc = Forrest::sobjects($object . '/describe');

        if (!isset($desc['fields']))
            return [];

        foreach ($desc['fields'] as $f) {
            if ($f['name'] == $field) {
                $values = [];
                foreach ($f['picklistValues'] as $p) {
                    $values[$p['value']] = $p['label'];
                }
                return $values;
            }
        }
        return [];
    }`

**Comment by roblesterjr04** [comment]
This is excellent. Would you mind if I include it in the package?

**Comment by seankndy** [comment]
Go for it.

**Comment by axsweet** [comment]
Would love to have you make these editable with a method, also there is a static non static issue sometimes could be addressed
