### ISSUE TITLE
Queries taking too long

### ISSUE THREAD

**Issue by lacrc** [roblesterjr04/EloquentSalesForce#2]
Hi! First, thanks for the package I was looking for something just like this!

My issue: I tried querying my Salesforce instance for Contacts but the query took sooo long.

I followed the steps in the installation and then:
`Contact::all()`
It took 4 minutes to finish and return 232 Contacts.
Is this the normal behavior? Can I do anything to speed it up?

**Comment by roblesterjr04** [comment]
Try limiting the query to specific columns, instead of the default view columns:

`Contact::select('Id', 'Name', 'Email')->get();`

Let me know how that plays out.

**Comment by roblesterjr04** [comment]
Which authentication method are you using, by the way?

**Comment by roblesterjr04** [comment]
Ok, sorry for the spam.

I think i found the issue. Each model, when instantiated, woudl call the authentication method for the SF library - i think that was in error. 

I've moved some code around, and i'm seeing a huge improvement. Will you require the `dev-master` branch and let me know if that improves your situation?

**Comment by lacrc** [comment]
Hey! Sorry for replying so late. Apparently I didn't even get spam due to not receiving github notifications (ops).

But Anyway: 
> Which authentication method are you using, by the way?
I'm using the user/password authentication.

> Will you require the dev-master branch and let me know if that improves your situation?
I used the dev-master branch and the query time is indeed waaay better!
Using `Contacts::all()` same as before and it took 3.4 seconds. I believe the issue is resolved!

Thanks again for this fix! :)
