### ISSUE TITLE
accessors don't seem to work at all

### ISSUE THREAD

**Issue by adrienne** [roblesterjr04/EloquentSalesForce#21]
On my Salesforce object, I have a column `Website_Availability__c`. I have it named in `$columns = []` and accessing it directly works just fine! However, I'd like to write an accessor for it so that I can refer to it elsewhere as just `availability_label`. The general format for accessors looks like this:

```php
  public function getAvailabilityLabelAttribute()
  {
    return $this->attributes['Website_Availability__c'];
  }
```

When I try this, I get 

```ErrorException (E_WARNING)
in_array() expects parameter 2 to be array, string given
```

Stack trace says it's line 38 of this file: `/vendor/rob-lester-jr04/eloquent-sales-force/src/Database/SOQLBuilder.php` that's causing the error. 

I can work around this for now but I would definitely really like it if accessors (and mutators, which I'm guessing are going to have the same issue) would work properly!

**Comment by adrienne** [comment]
@roblesterjr04 ?

**Comment by roblesterjr04** [comment]
This is odd because I definitely have done this myself. Let me review some of my other code. Can you share more of yours? Like the entire model?

**Comment by roblesterjr04** [comment]
The issue must be something else in your model. I can't reproduce it. The code that is throwing the error is at the api level anyway, not the accessor level. I did a quick test here
![image](https://user-images.githubusercontent.com/6423115/64736508-ca9f0180-d4b8-11e9-9326-c6321ae0eb47.png)
