### ISSUE TITLE
Array Pluck Function Missing in Laravel 6.0.3.

### ISSUE THREAD

**Issue by mikebrandl** [roblesterjr04/EloquentSalesForce#23]
Hi, 

After upgrading to laravel 6 adding a lead doesnt work.

Could you take a look please? 

Thanks

Mike

{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "message": "Call to undefined function Lester\\EloquentSalesForce\\array_pluck()",
    "code": 0,
    "file": "\/var\/www\/website\/vendor\/rob-lester-jr04\/eloquent-sales-force\/src\/ServiceProvider.php:54",
    "trace": [
        "\/var\/www\/website\/vendor\/rob-lester-jr04\/eloquent-sales-force\/src\/Database\/SOQLBuilder.php:123",
        "\/var\/www\/website\/vendor\/rob-lester-jr04\/eloquent-sales-force\/src\/Database\/SOQLBuilder.php:38",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php:505",
        "\/var\/www\/website\/app\/Http\/Controllers\/QuoteController.php:1303",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php:54",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php:45",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php:219",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php:176",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php:680",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:130",
        "\/var\/www\/website\/app\/Http\/Middleware\/ClearanceMiddleware.php:112",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:171",
        "\/var\/www\/website\/vendor\/laravel\/passport\/src\/Http\/Middleware\/CreateFreshApiToken.php:50",
        "\/var\/www\/website\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php:171",
        "\/var\/www\/website\/vendor\/laravel\/fra

**Comment by mikebrandl** [comment]
Just installed laravel/helpers, this resolved the issue.

**Comment by masoodvahid** [comment]
According to [this document](https://laravel.com/docs/8.x/helpers#method-array-pluck) you should use 
`Arr::pluck` in Laravel 8.x
