### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by Tamrael** [roblesterjr04/EloquentSalesForce#28]
we would like to upgrade our project to laravel 6.0 but this package which we depend on is not yet ready for the switch.

#27 is a pull request to add laravel 6.0 support, maybe this can help in getting this package updated?

**Comment by roblesterjr04** [comment]
This package depends on another package that will need to support 6.0. I will update as soon as both packages support 6.0

**Comment by roblesterjr04** [comment]
Configure your app to pull `dev-support60` to enable package support for Laravel 6. My tests are succeeding but i'd like to see it in practice and I don't have any L6 apps yet. Let me know.

**Comment by Tamrael** [comment]
Tested dev-support60 on the upgraded branch of our app an everything worked just fine. forrest seems to support 6.0 without needing any changes

**Comment by roblesterjr04** [comment]
Yeah, i determined that when i did some testing. It was still a valid concern  though. I'll make a release this week.
