### ISSUE TITLE
omniphx/forrest configurations

### ISSUE THREAD

**Issue by lacrc** [roblesterjr04/EloquentSalesForce#3]
Hi again!
Sorry for bothering, but is it possible to tweak the configuration for omniphx/forrest using your eloquent? I tried publishing their config file but it seems the configurations I made are not being loaded.

Thanks!

**Comment by roblesterjr04** [comment]
If you'll provide for me some details of what you're trying to override, i can see if i can make a way to do so. I'm working on some updates to the package as we speak, so nows a good time to include that.

**Comment by roblesterjr04** [comment]
@lacrc

**Comment by lacrc** [comment]
In my case I was trying to change the `expire_in` value of the storage session in forrest config. I wanted a longer time for the cache to expire. But maybe all the configuration in the publish config from omniphx/forrest might be useful for other people? I dunno.

Also thank you again for this package and for working on it still! :)
Great job!

**Comment by roblesterjr04** [comment]
Ahh, well each call my package makes re-authenticates so you shouldn't need it. But even so, grab the latest version because you can now publish the config from this package, and override the forrest configs directly in there.

**Comment by lacrc** [comment]
Oh that's awesome thanks!

On a side note, is there like a check before attempting to re-authenticate? Either by your package or forrest?
I think it could save a few more seconds in case of many different models/objects being called in the same controller. Or even multiple users? Not sure if Laravel saves the auth token app-wide or on a per-user basis. But since the token is cached, something like:
```
/**
 * Authenticates Forrest
 */
private function authenticateForrest()
{
    if (config('eloquent_sf.forrest.storage.type') === 'cache' && 
            !Cache::has(config('eloquent_sf.forrest.storage.path').'token')) // <- I think it's named prefix.'token'
        Forrest::authenticate();
}
```
Maybe that'll save a few seconds? Or something in the likes of that.
Anyway, just and idea.

This issue (about the config) afaik can be closed!
Thanks again!

**Comment by roblesterjr04** [comment]
@lacrc  Let me review his code, it actually may already do that.

**Comment by roblesterjr04** [comment]
@lacrc If you'd like, require `master-dev` The latest features/optimizations will include a wrapped authentication method that uses your code to check the token existance before authenticating again. Additionally, the method: `SObjects::authenticate()` is exposed if you want to use it, and it will return the token details, including bearer, if you need to do any super custom calls - all though that is not really needed since you can now call any Forrest method through the SObjects facade. This facade offers (docs will show this soon) a method to bulk update SF objects.
