### ISSUE TITLE
str_replaceLast

### ISSUE THREAD

**Issue by Tamrael** [roblesterjr04/EloquentSalesForce#30]
This function doesn't exist and never has. Seems like the Str::replace to str_replace caught this one

https://github.com/roblesterjr04/EloquentSalesForce/blob/bfe576ec00cf004c5e04a1e3a6909a05e612cf0d/src/Database/SOQLGrammar.php#L159

maybe this function part of the function should be covered by tests as well by using a table on the test that ends in "try" to trigger the if?

**Comment by roblesterjr04** [comment]
I fixed this in the latest release, sorry it took so long to see this.

Please upgrade to `^2.3`

**Comment by Tamrael** [comment]
No Problem, wasn't a bug that affected me, just one that caught my eye. Keep up the great work
