### ISSUE TITLE
updateOrCreate equivalent

### ISSUE THREAD

**Issue by floflock** [roblesterjr04/EloquentSalesForce#31]
If Salesforce Duplicate Rules are active, save action of an SObject throws an client exception. Therefore `Lead::updateOrCreate($attributes = [], $values = [])` is needed to query existing record before and update it, otherwise save it.

**Comment by roblesterjr04** [comment]
This method already exists. Have you tried it? Are you getting an error? Are you using the latest version? (2.*)
