### ISSUE TITLE
Using 2 Salesforce sessions concurrently

### ISSUE THREAD

**Issue by Otienoh** [roblesterjr04/EloquentSalesForce#33]
Can we swap the connections details when working with two different SalesForce instances?

i.e.
```php
'soql_region_1' => [
            'driver' => 'soql',
            'database' => null,
           ...
],

'soql_region_2' => [
            'driver' => 'soql',
            'database' => null,
           ...
],
``` 

The idea is to be able to swap the connections on the fly like so

```php
$region1Leads = \App\SaleforceModels\Lead::on('soql_region_1')->get();

$region2Leads = \App\SaleforceModels\Lead::on('soql_region_2')->get();
```

At the moment with the current set up, when running the above code I get the error below
```php
 local.ERROR: InvalidArgumentException: Unsupported driver [soql] in ...\Database\Connectors\ConnectionFactory.php:283
```

Any ideas on how to fix or achieve the result?

**Comment by roblesterjr04** [comment]
Interesting idea.

Currently the package isn't going to support that without hacking around it, but i'll keep that in mind in near term updates. 

You may be able to swap configs on demand by calling `config(['database.connections.soql' => [...new connection info])`

**Comment by Otienoh** [comment]
great good job.

Should I close the issue or keep it open for tracking?
