### ISSUE TITLE
using batch functionality causes exception

### ISSUE THREAD

**Issue by m-lotze** [roblesterjr04/EloquentSalesForce#35]
I am trying to use the batch method, but it always throws this exception:

```
Omniphx\Forrest\Exceptions\SalesforceException
[ { "message": "The Content-Encoding of the message specifices GZIP, but the data is not in valid GZIP format", "errorCode": "UNKNOWN_EXCEPTION" } ]
```

I tried to change the config to `'eloquent_sf.forrest.defaults.compression' => false` and `'eloquent_sf.forrest.defaults.compressionType' => null`, but this has no effect.

**Comment by roblesterjr04** [comment]
I will look in to it. I don't see any reason why you would get the error only on the batch though. What version of SalesForce are you using?

**Comment by roblesterjr04** [comment]
I think its backwards. Try enabling compression and setting `gzip` as the compression type. Seems these settings describe how to read the response, not how to send the request. I wonder if your salesforce instance is enabling compression at the API level.

**Comment by m-lotze** [comment]
I am using a trailhead playground. this is the simple function in my testcontroller:

```
class TestController extends Controller
{
    public function test()
    {
        config(['eloquent_sf.forrest.defaults.compression' => true]);
        config(['eloquent_sf.forrest.defaults.compressionType' => 'gzip']);

        Contact::select(['Id', 'FirstName', 'LastName'])->limit(1)->batch();
        Lead::select(['Id', 'FirstName', 'Company'])->limit(1)->batch();

        $batch = SObjects::runBatch();

        dd($batch->results('Lead'), $batch->results('Contact'));
    }
}
```
It does not matter which setting/combination for config i use, the error is always the same as soon as i am trying to use the batch function. this e.g. works with any config:

```
public function test()
{
    config(['eloquent_sf.forrest.defaults.compression' => false]);
    config(['eloquent_sf.forrest.defaults.compressionType' => null]);

    dd(Contact::select(['Id', 'FirstName', 'LastName'])->first());
}
```

**Comment by roblesterjr04** [comment]
Try setting the config values in the config file itself - by the time you call the config method in the controller, the settings from the `eloquent_sf.forrest` config have already been sent to the forrest serviceprovider. (line 28 in the ServiceProvider)

**Comment by roblesterjr04** [comment]
Or you could also just change your callout to `config(['forrest.defaults.compression' => false]);`

**Comment by m-lotze** [comment]
I removed my settings and left the config to default and now it is working. maybe compression should not be used.

**Comment by roblesterjr04** [comment]
The compression is not on the plugin side, its on the SF side, so we don't have any control in the package other than setting the settings to match.

**Comment by nickturrietta** [comment]
I had, and still have, this same problem. This is how I have resolved it..

src/Omniphx/Forrest/Client.php 
https://github.com/sdrockdev/forrest/commit/f0ba40b7da52649525caaefed7778a00746e99f6

**Comment by roblesterjr04** [comment]
Once Marty pulls in your PR It should work then.
