### ISSUE TITLE
Backticks in the SOSQL causing error

### ISSUE THREAD

**Issue by mattlanham** [roblesterjr04/EloquentSalesForce#4]
I'm having an issue where the generated SOSQL contains backticks (`) around column names, and table names. I have run the generated query through the developer console inside of Salesforce and it also fails, until I remove the backticks?

The offending query is:
```SELECT `Id` FROM `Account` LIMIT 1```

The query that works based on Salesforce developer console is:
```SELECT Id FROM Account LIMIT 1```

Any thoughts?

**Comment by mattlanham** [comment]
Also just to further this, if the value is a number it is unquoted by eloquent, but for SF it must be quoted, without any changes the following SOSQL fails:

```SELECT `Id` FROM `Account` WHERE `Id` = 12345 LIMIT 1```

for SOSQL to work it needs to be:

```SELECT Id FROM Account WHERE Id = '12345' LIMIT 1```

**Comment by roblesterjr04** [comment]
Generally the reported query is not the actual query getting sent to salesforce. I generally found that i needed to look in to the system logs to see the error salesforce was actually reporting. I did not implement custom error controls so basically most error reports from laravel will include the query it assembles. later on in the connector process i'm removing the back ticks.

**Comment by mattlanham** [comment]
I adjusted the code in the library to remove the ticks, and it worked perfectly, it's odd that you aren't seeing the same result - what version of Laravel / Eloquent are you using - perhaps it's that I am on the latest version.

**Comment by roblesterjr04** [comment]
Hmm. no, because i've been working with the latest version myself, so i don't think thats it. If you notice improvements by doing this, i don't see why it shouldn't be there :) If you do a PR i'll merge it in.
