### ISSUE TITLE
SOQLBatch has issue with Laravel 7.0

### ISSUE THREAD

**Issue by arazakalhoro** [roblesterjr04/EloquentSalesForce#40]
got following exception when trying to get records
Exception: Declaration of Lester\EloquentSalesForce\Database\SOQLBatch::push($builder) should be compatible with Illuminate\Support\Collection::push(...$values)

File: SOQLBatch.php
Line: 49 
Function: push($builder)

**Comment by JasonMaitlen** [comment]
I too had the same issue. In the eloquent-sales-force\src\Database\SOQLBatch.php I changed the push function declaration from:

`public function push($builder)`

to 

`public function push(...$builder)`

and this fixed this error for me.

I'm new to this package though and having other errors, so I'm not sure if this truly fixes the issue.

**Comment by baldhadhaval08** [comment]
@roblesterjr04 Can you please update this change to fix issue in Laravel 7?

**Comment by JasonMaitlen** [comment]
Even once I fixed this issue I ran into others. I suspect the whole package may need updated to be compatible with Laravel 7.

**Comment by roblesterjr04** [comment]
Hi all, Laravel 7 is very new, so it will take time to update and make it compatible. Thank you for the headstart!

**Comment by arazakalhoro** [comment]
Thanks, it works for me
