### ISSUE TITLE
Bump Guzzle

### ISSUE THREAD

**Issue by mikebrandl** [roblesterjr04/EloquentSalesForce#57]
Hi, 

Can we please bump Guzzle to 7.0.1 so that we can go to Laravel 8? 

Thanks

Mike

**Comment by Arametheus** [comment]
also adding to this.. as Laravel 6 is also upgraded to Guzzle 7.0.1, so you can't install the package.

**Comment by roblesterjr04** [comment]
Issue has been resolved. Please pull the latest version.
