### ISSUE TITLE
Is there any way to avoid "UNABLE_TO_LOCK_ROW" error every once in a while?

### ISSUE THREAD

**Issue by stzahi** [roblesterjr04/EloquentSalesForce#59]
I get this error every once in a while and it's very annoying.
`"message": "unable to obtain exclusive access to this record or 1 records: 001XXXXXXXXXXXXXX",
 "errorCode": "UNABLE_TO_LOCK_ROW",`
I can see that Salesforce API has some kind of solution for this error that sets the API to wait for the row to be released.
Is there any implementation for it in this package? any way to avoid it?

Thank you!

**Comment by roblesterjr04** [comment]
@stzahi So this is an issue working with records in your system. There seems to be some race conditions. I did look in to locking records and it looks like as far as SFDC is concerned, you can't lock records when working with them through the API. They deem the request complete once the data has been returned, and that no other operations will be performed.
