### ISSUE TITLE
Impossible to connect with UserPassword

### ISSUE THREAD

**Issue by franz177** [roblesterjr04/EloquentSalesForce#66]
Hello,

I need to log in via the UsernamePassword method. But every time I get this error:

**`POST https://test.salesforce.com/services/oauth2/token` resulted in a` 400 Bad Request` response: `{"error": "invalid_grant", "error_description": "authentication failure"}`**

Code in the .env file:

```
CONSUMER_KEY = XXXXXXXXXXXXXXX
CONSUMER_SECRET = XXXXXXXXXXXX
CALLBACK_URI = https: //app.laravel.test/callback

LOGIN_URL = https: //test.salesforce.com (sandbox)

username=xxxxxxx@xxxxxx.xx.xxxx
PASSWORD = PasswordAndTokenWithoutSpace
```

Code in config/database.php

```
'soql' => [
            'driver' => 'soql',
            'database' => null,
            'consumerKey'    => env('CONSUMER_KEY'),
            'consumerSecret' => env('CONSUMER_SECRET'),
            'callbackURI' => env('CALLBACK_URI'),
            'loginURL'       => env('LOGIN_URL'),
            // Only required for UserPassword authentication:
            'username'       => env('USERNAME'),
            // Security token might need to be ammended to password unless IP Address is whitelisted
            'password'       => env('PASSWORD')
        ],
```

These are the API (Enable OAuth Settings) configurations on salesforce:

![image](https://user-images.githubusercontent.com/60187197/127659943-0d850f4c-261f-4ee4-9496-b5c18c596a87.png)

**Comment by axsweet** [comment]
need to go to your account, theres a way just on hte front end and you can append the security key to your password in the config.
