### ISSUE TITLE
Trouble with the Query Builder, order of where clauses, and the resulting query parameters

### ISSUE THREAD

**Issue by nickturrietta** [roblesterjr04/EloquentSalesForce#75]
![141025271-454ad667-78b2-409c-acde-b9b3a0956c62](https://user-images.githubusercontent.com/6426374/141025641-7a2ffe6b-089e-4018-9554-ffdc0bdd000a.png)

See attached. This is a weird bug that I ran into today. (Not sure if it is just specific to queries that involve dates)

FWIW, I think this is something that was introduced within the last year, as I have been using this package for a while and just recently updated.

**Comment by roblesterjr04** [comment]
looking in to this now.

**Comment by roblesterjr04** [comment]
@nickturrietta  Holy crap that was tough, i've got some docs to update. Pull down `dev-master` and let me know if that solves your issues.

I will be removing support for the "shortDates" declaration - when querying long vs short dates, you would simply use `where` and `whereDate` respectively - the Laravel `whereDate` method on the query builder automatically formats to the short date, while `where` follows the declared format in the grammar, which is `Y-m-d\TH:i:s\Z`

**Comment by nickturrietta** [comment]
@roblesterjr04 Awesome! Confirmed all is good again. Thanks Rob.

PS. I made an attempt to fix last night, but failed after a few hours. So, I guess, in a sense, I'm happy that it wasn't like something completely obvious. Appreciate you.

**Comment by roblesterjr04** [comment]
Yeah i had to back track quite a bit. These issues are great because its actually pushing the package to leverage more native laravel functionality. Thanks for flagging and for the detailed troubleshooting.

**Comment by nickturrietta** [comment]
Glad to hear it.. thanks again!
