### ISSUE TITLE
Issue with onlyTrashed method and the resulting query parameters

### ISSUE THREAD

**Issue by nickturrietta** [roblesterjr04/EloquentSalesForce#78]
Hey Rob, here is an issue I stumbled on with the onlyTrashed method for soft deletes, related to the order of eloquent method calls and resulting query parameters.

![screencap](https://user-images.githubusercontent.com/6426374/142961157-3ca91b3d-4a29-4e28-98f3-ed840315d62f.png)

**Comment by nickturrietta** [comment]
You might have already fixed this

**Comment by roblesterjr04** [comment]
@nickturrietta thanks for raising, i think i found the issue, can you please pull `dev-master` and see if that resolves it?

**Comment by nickturrietta** [comment]
@roblesterjr04 just pulled dev-master, and gave it a shot, but it doesn't seem to have resolved it.

**Comment by roblesterjr04** [comment]
Hmm

**Comment by roblesterjr04** [comment]
@nickturrietta pull dev master and try again for this issue. I was able to reproduce and fix unil issue was gone.

**Comment by nickturrietta** [comment]
@roblesterjr04 Yes! that did the trick. Thanks Rob!
