### ISSUE TITLE
Please add Laravel 9 support

### ISSUE THREAD

**Issue by stzahi** [roblesterjr04/EloquentSalesForce#84]
:pray: 

Is there an expectation? 

Thanks, and thanks for a great library.

**Comment by roblesterjr04** [comment]
I've already provided that support - can you submit any errors you're experiencing?

![image](https://user-images.githubusercontent.com/6423115/167164259-489abe90-c671-40f7-b78f-1778411dc59a.png)

**Comment by roblesterjr04** [comment]
@stzahi please review my comment above.

**Comment by Wit3** [comment]
@roblesterjr04 f i try to install in a L9 project ( updated to latest version ) i receive this error

```
- rob-lester-jr04/eloquent-sales-force[2.14.0, ..., 2.14.3] require laravel/framework ^6.0 || ^7.0 || ^8.40.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.40.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.11).
```

**Comment by roblesterjr04** [comment]
@Wit3 Release is out, 2.14.4

**Comment by Wit3** [comment]
Thanks @roblesterjr04 !
I've point to tag 2.14.4

But this is tag not release

Latest Release is:

![image](https://user-images.githubusercontent.com/5450259/167887357-9d039355-4432-4db8-b1bf-c382ae3b05b0.png)

**Comment by roblesterjr04** [comment]
Symantics - Composer will still grab the latest or specified tag.

**Comment by stzahi** [comment]
@roblesterjr04 I don';t know the reason I didn't get any notification about your replies. Sorry for coming back so late =\

I'll try to install it again now and I'll let you know.

Thankyou!
