### ISSUE TITLE
describe not returning all the fields (including custom fields)

### ISSUE THREAD

**Issue by rajjanorkar** [roblesterjr04/EloquentSalesForce#9]
describe not returning all the fields (including custom fields)

Tried below:

```
- Account::describe(true)
-  SObjects::object('Account')->describe();
-  SObjects::object('Account')->describe(true);

```
etc

Not sure it is bug or i am doing something wrong.

Thank you.

**Comment by jayomayan** [comment]
Any update on this one?
Tried it too and it seem like it only returns a portion of the fields.

**Comment by jayomayan** [comment]
Tried 

$leadFields = Lead::describe();

and this is the result:
Array ( [0] => Id [1] => Salutation [2] => FirstName [3] => MiddleName [4] => LastName [5] => Suffix [6] => Company [7] => Phone [8] => Email ) 1

**Comment by seankndy** [comment]
Documentation goes over this.  https://github.com/roblesterjr04/EloquentSalesForce -- scroll down to "Columns"
