### ISSUE TITLE
Bug when concatenating timestamp fields

### ISSUE THREAD

**Issue by IdrisN** [roblesterjr04/EloquentSalesForce#93]
https://github.com/roblesterjr04/EloquentSalesForce/blob/ab0615833b6259b6dc4ddd360f41dc483d3bbe3a/src/Database/SOQLBuilder.php#L80

I assume the intention here is to concat the columns with `['CreatedDate', 'LastModifiedDate']` but since the `+`-operator replaces array elements w.r.t. their keys, the concatenation does not work as intended.

For example:
```php
['Id'] + ['CreatedDate', 'LastModifiedDate'] == ['Id', 'LastModifiedDate'] // true

```
[Here](https://stackoverflow.com/a/2140094) is a good explaination.

Sidenote:
I've came across this because i had an error when trying to use EloquentSalesforce models which do not have `CreatedDate` or `LastModifiedDate` fields (e.g. `ContentDocumentLink`).

**Comment by alexardalich** [comment]
I just hit this myself after a composer update moving to php8.1, looking at upgrading to Laravel 10.
CreatedDate and LastModifiedDate being added to the $cols array, causing an error fetching salesforce models which do not have those fields.

Change is in https://github.com/roblesterjr04/EloquentSalesForce/commit/4c0f82f56010aeeee68d4f96c6c7f36c71b00cc2
