### ISSUE TITLE
Problem with (unescaped) single quotes in query

### ISSUE THREAD

**Issue by antonio-bp** [roblesterjr04/EloquentSalesForce#95]
When I filter for a field with a single quote, I get an unexpected error.

Example:
Searching first account with the name `A'name`:

```php
Account::where('Name', "A'name")->limit(1)->get();
```

will throws: 
`Lester\EloquentSalesForce\Exceptions\MalformedQueryException`

![image](https://user-images.githubusercontent.com/57486624/235158350-924d10b6-a6e8-4c2b-8577-4cc23567e784.png)

**Comment by antonio-bp** [comment]
A temporary solution:

1. Create a **CustomQueryBuilder**

```php
use Illuminate\Database\Query\Builder;

/**
 * Tmp fix for this issue:
 * https://github.com/roblesterjr04/EloquentSalesForce/issues/95
 */
class CustomQueryBuilder extends Builder
{

    public function getBindings()
    {
        return array_map(
            fn ($value) => \Str::replace("'", "\'", $value),
            parent::getBindings()
        );
    }

}
```

2. Create a trait that overwrite `getBindings` method:

```php
use App\Builders\CustomQueryBuilder;

trait HasCustomQueryBuilder
{

    protected function newBaseQueryBuilder()
    {
        $connection = $this->getConnection();

        return new CustomQueryBuilder(
            $connection,
            $connection->getQueryGrammar(),
            $connection->getPostProcessor()
        );
    }

}
```

3. Use the trait in all your Model, for example:

```php
namespace App\Models\SF;

use App\Traits\HasCustomQueryBuilder;
use Lester\EloquentSalesForce\Model;

class Account extends Model
{
    use HasCustomQueryBuilder;
```

**Comment by shez1983** [comment]
i know this is solved, but i have recently (last week) started using this repo and when i do model::where...  i can see it uses laravels eloquent model function where.. so i am not sure why escapin isnt happening, 

if i do laravelMode::where('name'... ) that works but if i have a model using this repo then it doesnt.. :/

**Comment by antonio-bp** [comment]
> i know this is solved, but i have recently (last week) started using this repo and when i do model::where... i can see it uses laravels eloquent model function where.. so i am not sure why escapin isnt happening,
> 
> if i do laravelMode::where('name'... ) that works but if i have a model using this repo then it doesnt.. :/

Sorry, but I'm not sure I understand.
Can you explain it with an example (with query and with the error)?

**Comment by caseydwyer** [comment]
@antonio-bp how confident are you that this fixed the issue? V possible I'm doing something weird, here...but it seems pretty straightforward. We have a `where` clause that works without a `'` character. But it fails with `O'Connor` as the last name:
```php
from Contact where (LastName = 'O'Connor' or csp__Initiated_Last_Name__c ^ ERROR at Row:1:Column:425 expecting a right parentheses, found 'Connor'
```
Looking at the stacktrace, I don't think your updated `toSql()` method is ever called. Instead, that's being called from Laravel's `Illuminate/Database/Query/Builder`. Here's what we get from Bugsnag, if helpful:

![image](https://github.com/roblesterjr04/EloquentSalesForce/assets/13950848/139c8927-df16-4e3f-afc2-858a4f273c34)

The only call in this stack that I see being made to `SOQLBuilder` is the `getModels` method. Maybe that's helpful? Let me know if I'm missing something obvious, here, or if there's anything else I can provide or check to debug.
